#!/usr/bin/env bash

# Load the lcdsh library
source ~/lcdsh/lib/lcd.bash

# Connect to the LCDproc server
lcd_init_prompt || exit 1

# Greet the world
lcd_show "Hello world!"
# Or, an alternative: pipe the text to lcd_show function:
# echo "Hello world!" | lcd_show

# Listen for events from the LCDproc server
lcd_msg_loop
