#!/usr/bin/env bash

while true; do
    now=$(vnstat -tr 2 \
        | grep '^[[:space:]]*[r|t]x' \
        | awk '{printf "%s: %s %s\n", $1, $2, $3 }')
    totals=$(vnstat --oneline | awk -F';' '{printf "t_rx: %s\nt_tx: %s\n", $4, $5}')
    clear
    echo "${now}"
    echo "${totals}"
    echo "--"
done

